# Generated by Django 5.0.2 on 2025-05-22 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema_escolar_api', '0005_evento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evento',
            name='programa_educativo',
            field=models.CharField(blank=True, choices=[('Ingeniería en Ciencias de la Computación', 'Ingeniería en Ciencias de la Computación'), ('Licenciatura en Ciencias de la Computación', 'Licenciatura en Ciencias de la Computación'), ('Ingeniería en Tecnologías de la Información', 'Ingeniería en Tecnologías de la Información')], max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='evento',
            name='tipo',
            field=models.CharField(choices=[('Conferencia', 'Conferencia'), ('Taller', 'Taller'), ('Seminario', 'Seminario'), ('Concurso', 'Concurso')], max_length=100),
        ),
    ]
