# Generated by Django 5.0.2 on 2025-05-09 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema_escolar_api', '0005_maestros_edad_alter_alumnos_fecha_nacimiento_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='administradores',
            name='creation',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='administradores',
            name='update',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='alumnos',
            name='creation',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='alumnos',
            name='fecha_nacimiento',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='alumnos',
            name='update',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='maestros',
            name='creation',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='maestros',
            name='fecha_nacimiento',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='maestros',
            name='update',
            field=models.DateField(blank=True, null=True),
        ),
    ]
