# Generated by Django 5.0.2 on 2025-05-22 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema_escolar_api', '0006_alter_evento_programa_educativo_alter_evento_tipo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='evento',
            name='estudiantes',
        ),
        migrations.RemoveField(
            model_name='evento',
            name='fecha',
        ),
        migrations.RemoveField(
            model_name='evento',
            name='profesores',
        ),
        migrations.RemoveField(
            model_name='evento',
            name='publico_general',
        ),
        migrations.RemoveField(
            model_name='evento',
            name='responsable',
        ),
        migrations.RemoveField(
            model_name='evento',
            name='tipo',
        ),
        migrations.AddField(
            model_name='evento',
            name='fecha_evento',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='evento',
            name='publico_objetivo',
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='evento',
            name='responsable_evento',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='evento',
            name='tipo_evento',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='evento',
            name='cupo_maximo',
            field=models.CharField(blank=True, max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='evento',
            name='descripcion',
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='evento',
            name='hora_fin',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='evento',
            name='hora_inicio',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='evento',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='evento',
            name='lugar',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='evento',
            name='nombre',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='evento',
            name='programa_educativo',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
