# Generated by Django 5.0.2 on 2025-05-22 15:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sistema_escolar_api', '0007_remove_evento_estudiantes_remove_evento_fecha_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='evento',
            old_name='fecha_evento',
            new_name='fecha',
        ),
        migrations.RenameField(
            model_name='evento',
            old_name='tipo_evento',
            new_name='tipo',
        ),
    ]
