# Generated by Django 5.0.2 on 2025-05-09 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema_escolar_api', '0007_alter_administradores_creation_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='maestros',
            name='edad',
        ),
        migrations.AlterField(
            model_name='alumnos',
            name='fecha_nacimiento',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='alumnos',
            name='matricula',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='maestros',
            name='fecha_nacimiento',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='maestros',
            name='id_trabajador',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='maestros',
            name='materias_json',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
